// Package audit holds the persistence entity for the HLD-010 audit trail.
// One row per (actor, action, resource, outcome) observation. The whole
// point of this table is to be unforgeable record-keeping for "who did
// what" — code in this package must never mutate or delete rows except via
// the retention job.
//
// The action vocabulary that used to be spelled out here now lives in
// core/base/pkg/audit and is re-exported below, so a handler in
// another bounded context can name a row without importing this package
// (decision 109). The GORM entities stayed: they are storage, not
// vocabulary, and nothing outside data/audit/store has any business
// knowing that this table is called audit_logs.
package audit

import (
	"time"

	auditport "github.com/vincent-wuhan/opskeeper/core/base/pkg/audit"
)

// Log is one audit observation.
//
// Field-level notes:
//
//   - UserID is *uint64 so the unauthenticated-actor path (failed login,
//     anon endpoint) can write NULL and still satisfy the FK semantics
//     a future migration may add.
//   - All TEXT columns are NOT NULL but **without** a GORM-level
//     default:” tag — MySQL 8 rejects DEFAULT on TEXT (Error 1101), as
//     tripped by v0.7.43's investigation_report migration. Go's zero
//     value for string is "" so NOT NULL is satisfied at insert time.
//   - PayloadJSON is the only free-form field. The biz layer must
//     redact secrets BEFORE serialising (LLM keys, SSH keys, passwords,
//     tokens). What lives here is the **shape** of the change, not the
//     values — e.g. {"field":"openai_api_key","action":"set","hint":"sk-...XYZ"}.
//   - RequestID is the same id stamped onto the request's structured
//     log entries by the chi RequestID middleware (or generated by the
//     audit middleware itself when no upstream id exists). Lets an
//     operator join an audit row back to slog / future tracing output.
type Log struct {
	ID           uint64    `gorm:"primaryKey;autoIncrement"`
	OccurredAt   time.Time `gorm:"not null;index:idx_audit_occurred"`
	UserID       *uint64   `gorm:"index:idx_audit_user,priority:1"`
	UserEmail    string    `gorm:"size:255;not null"`
	Role         string    `gorm:"size:16;not null"`
	IP           string    `gorm:"size:45;not null"`
	UserAgent    string    `gorm:"size:512;not null"`
	Action       string    `gorm:"size:64;not null;index:idx_audit_action,priority:1"`
	ResourceType string    `gorm:"size:32;not null;index:idx_audit_resource,priority:1"`
	ResourceID   string    `gorm:"size:128;not null;index:idx_audit_resource,priority:2"`
	ResourceName string    `gorm:"size:256;not null"`
	Status       string    `gorm:"size:16;not null;index:idx_audit_status,priority:1"`
	ErrorCode    string    `gorm:"size:64;not null"`
	ErrorMessage string    `gorm:"size:512;not null"`
	PayloadJSON  string    `gorm:"type:text"`
	RequestID    string    `gorm:"size:64;not null"`
	CreatedAt    time.Time `gorm:"autoCreateTime"`

	// Chain columns. HLD-010's tamper-evidence lives here: Seq is the
	// row's position in the append-only chain, PrevHash is the Hash of
	// the row before it, and Hash is the keyed digest over both plus
	// every field above. Editing any field of any row invalidates that
	// row's Hash and therefore every Hash after it, so a deletion or an
	// edit cannot hide behind a later row that still looks plausible.
	//
	// Seq is 0 on rows written before the chain was switched on. Zero is
	// the "unchained" marker rather than a position, which is what lets
	// the chain be introduced on a live table without a backfill that
	// would have to invent a history nobody can verify anyway.
	Seq      uint64 `gorm:"not null;default:0;index:idx_audit_seq"`
	PrevHash string `gorm:"size:64;not null;default:''"`
	Hash     string `gorm:"size:64;not null;default:''"`
}

// ChainHead is the single row that serialises the hash chain.
//
// One row, id=1, holding the sequence number and hash of the most
// recently appended entry. It exists because a chain built from a
// cached in-process head forks the moment a second manager instance
// writes: both read the same head, both stamp the same PrevHash, and
// the result verifies as intact right up to the point where it is not.
// The head is instead advanced with a compare-and-swap on Seq inside
// the same transaction that inserts the entry, so a writer that lost
// the race fails its update, reads the new head, and retries — and a
// writer that crashes between the two leaves a head that is too high
// rather than an entry that chains to nothing.
type ChainHead struct {
	ID        uint64    `gorm:"primaryKey;autoIncrement:false"`
	Seq       uint64    `gorm:"not null;default:0"`
	Hash      string    `gorm:"size:64;not null;default:''"`
	UpdatedAt time.Time `gorm:"autoUpdateTime"`
}

// TableName pins the head table. The constant name is spelled out in
// code rather than left to GORM's pluraliser so a rename of the model
// cannot silently orphan every writer's head.
func (ChainHead) TableName() string { return "audit_chain_head" }

// ChainHeadID is the fixed primary key of the one head row. It is not
// an auto-increment sequence: there is exactly one head, and a second
// one would mean two chains.
const ChainHeadID uint64 = 1

// TableName pins the table so a package rename doesn't silently create a
// parallel empty table.
func (Log) TableName() string { return "audit_logs" }

// The action / resource / status vocabulary below was moved to
// core/base/pkg/audit in decision 109 and is re-exported here rather
// than duplicated. Two things depend on it being one definition: the
// middleware buckets an HTTP status into Status* before the writer ever
// sees the row, and iam's handlers name actions from another bounded
// context — which is exactly why the constants cannot live above them.
// A const alias is a compile-time identity, so a row written with
// auditmodel.ActionUserCreate and a row written with
// auditport.ActionUserCreate are the same string by construction, not by
// a test that would eventually be forgotten.
const (
	StatusSuccess = auditport.StatusSuccess
	StatusFailure = auditport.StatusFailure
	StatusDenied  = auditport.StatusDenied

	ActionAuthLoginFailed = auditport.ActionAuthLoginFailed

	ActionUserCreate = auditport.ActionUserCreate
	ActionUserUpdate = auditport.ActionUserUpdate
	ActionUserDelete = auditport.ActionUserDelete
	ActionUserExport = auditport.ActionUserExport

	ActionDeviceUpdate = auditport.ActionDeviceUpdate
	ActionDeviceDelete = auditport.ActionDeviceDelete

	ActionRuleCreate = auditport.ActionRuleCreate
	ActionRuleUpdate = auditport.ActionRuleUpdate
	ActionRuleDelete = auditport.ActionRuleDelete

	ActionIncidentAck     = auditport.ActionIncidentAck
	ActionIncidentResolve = auditport.ActionIncidentResolve
	ActionIncidentSilence = auditport.ActionIncidentSilence

	ActionSettingUpdate = auditport.ActionSettingUpdate
	ActionSettingDelete = auditport.ActionSettingDelete

	ActionChannelCreate = auditport.ActionChannelCreate
	ActionChannelUpdate = auditport.ActionChannelUpdate
	ActionChannelDelete = auditport.ActionChannelDelete

	ActionRepoCreate = auditport.ActionRepoCreate
	ActionRepoDelete = auditport.ActionRepoDelete
	ActionRepoSync   = auditport.ActionRepoSync

	ActionSkillInstall   = auditport.ActionSkillInstall
	ActionSkillUninstall = auditport.ActionSkillUninstall

	ActionPluginReleaseStart    = auditport.ActionPluginReleaseStart
	ActionPluginReleaseAdvance  = auditport.ActionPluginReleaseAdvance
	ActionPluginReleaseHalt     = auditport.ActionPluginReleaseHalt
	ActionPluginReleaseRollback = auditport.ActionPluginReleaseRollback

	ActionAutonomyExecute = auditport.ActionAutonomyExecute

	ActionAgentTeamsTokenIssue = auditport.ActionAgentTeamsTokenIssue

	ActionMCPToolCall      = auditport.ActionMCPToolCall
	ActionMCPToolAuthorize = auditport.ActionMCPToolAuthorize

	ActionNodeToolCall        = auditport.ActionNodeToolCall
	ActionNodeToolBlocked     = auditport.ActionNodeToolBlocked
	ActionNodeToolFailed      = auditport.ActionNodeToolFailed
	ActionNodeApprovalRequest = auditport.ActionNodeApprovalRequest
	ActionNodeApprovalGrant   = auditport.ActionNodeApprovalGrant
	ActionNodeApprovalDeny    = auditport.ActionNodeApprovalDeny
	ActionNodeAgentTurn       = auditport.ActionNodeAgentTurn
	ActionNodeModelCall       = auditport.ActionNodeModelCall
	ActionNodePluginInstall   = auditport.ActionNodePluginInstall
	ActionNodePluginRemove    = auditport.ActionNodePluginRemove
	ActionNodePluginLoad      = auditport.ActionNodePluginLoad
	ActionNodeProposalCreate  = auditport.ActionNodeProposalCreate
	ActionNodeRecoveryApply   = auditport.ActionNodeRecoveryApply

	ActionAgentToolCall = auditport.ActionAgentToolCall

	ResourceUser     = auditport.ResourceUser
	ResourceDevice   = auditport.ResourceDevice
	ResourceIncident = auditport.ResourceIncident
	ResourceSetting  = auditport.ResourceSetting
	ResourceRule     = auditport.ResourceRule
	ResourceChannel  = auditport.ResourceChannel
	ResourceRepo     = auditport.ResourceRepo
	ResourceSkill    = auditport.ResourceSkill
	ResourceLLM      = auditport.ResourceLLM
	ResourceGitKey   = auditport.ResourceGitKey
	ResourceGrafana  = auditport.ResourceGrafana
	ResourceRAG      = auditport.ResourceRAG
	ResourceAudit    = auditport.ResourceAudit
	ResourceAuth     = auditport.ResourceAuth
	ResourcePlugin   = auditport.ResourcePlugin
	ResourceEdge     = auditport.ResourceEdge
	ResourceMCPTool  = auditport.ResourceMCPTool

	ResourceAgentTool = auditport.ResourceAgentTool
)
