#!/usr/bin/env python3
"""render-pi-system-md.py — render the opskeeper-monitor role contract
into a fresh Pi session at edge startup.

Reads the canonical role contract from
`opskeeper/pi-skills/opskeeper-monitor/AGENTS.md` and prepends a
runtime snapshot (host_info, last incident summary, edge version) so
Pi starts every session with situational awareness.

The output is written to:
  $OPSKEEPER_PI_AGENT_DIR/agents/opskeeper-monitor.md
defaulting to `vendor/pi/.pi/agents/opskeeper-monitor.md` if not set.

Exit codes:
  0 — rendered and wrote successfully
  1 — missing source AGENTS.md
  2 — render failed (output dir not writable)
"""
from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = REPO_ROOT / "pi-skills" / "opskeeper-monitor" / "AGENTS.md"
DEFAULT_TARGET_REL = Path("vendor/pi/.pi/agents/opskeeper-monitor.md")


def _host_snapshot() -> dict[str, str]:
    """Collect small host facts. No LLM calls, no network."""
    snap: dict[str, str] = {}
    snap["edge_id"] = os.environ.get("OPSKEEPER_EDGE_ID") or "edge-unknown"
    # Round to whole seconds so the --check comparator is stable
    # within a second (sub-second drift would make idempotent CI
    # verification impossible otherwise).
    snap["collected_at"] = (
        _dt.datetime.now(_dt.timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )

    try:
        snap["hostname"] = subprocess.run(
            ["hostname"], capture_output=True, text=True, timeout=2, check=True
        ).stdout.strip()
    except Exception:  # noqa: BLE001 — best-effort context
        snap["hostname"] = "unknown"

    try:
        snap["kernel"] = subprocess.run(
            ["uname", "-r"], capture_output=True, text=True, timeout=2, check=True
        ).stdout.strip()
    except Exception:  # noqa: BLE001
        snap["kernel"] = "unknown"

    snap["pi_version"] = os.environ.get("OPSKEEPER_PI_TAG_LOCK") or "v0.85.1"
    snap["edge_version"] = os.environ.get("OPSKEEPER_VERSION") or "dev"
    return snap


def _last_incident_line(incident_log: Path) -> str:
    if not incident_log.exists():
        return "_no prior incident on this edge_"
    try:
        # tail one line without slurping the whole file
        with incident_log.open("rb") as fh:
            fh.seek(0, os.SEEK_END)
            size = fh.tell()
            fh.seek(max(0, size - 4096))
            tail = fh.read().decode("utf-8", errors="replace")
        lines = [ln for ln in tail.splitlines() if ln.strip()]
        return lines[-1] if lines else "_empty incident log_"
    except OSError as exc:
        return f"_incident log unreadable: {exc}_"


def render(source: Path, target: Path, incident_log: Path) -> str:
    if not source.exists():
        raise SystemExit(f"source AGENTS.md not found: {source}")
    body = source.read_text(encoding="utf-8")
    snap = _host_snapshot()
    incident = _last_incident_line(incident_log)
    header = (
        "<!-- AUTO-GENERATED by scripts/render-pi-system-md.py — do not edit "
        "this file directly. Edit pi-skills/opskeeper-monitor/AGENTS.md and "
        "re-run this script. -->\n\n"
        f"# opskeeper-monitor snapshot @ {snap['collected_at']}\n\n"
        f"- edge_id: `{snap['edge_id']}`\n"
        f"- hostname: `{snap['hostname']}`\n"
        f"- kernel: `{snap['kernel']}`\n"
        f"- edge_version: `{snap['edge_version']}`\n"
        f"- pi_version: `{snap['pi_version']}`\n"
        f"- last_incident: {incident}\n\n"
        "---\n\n"
    )
    return header + body


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                   help=f"source AGENTS.md (default: {DEFAULT_SOURCE})")
    p.add_argument("--target", type=Path, default=None,
                   help="output path (default: $OPSKEEPER_PI_AGENT_DIR/agents/"
                        "opskeeper-monitor.md, fallback vendor/pi/.pi/agents/...)")
    p.add_argument("--incident-log", type=Path,
                   default=Path(os.environ.get("OPSKEEPER_INCIDENT_LOG", "/var/log/opskeeper/incidents.log")),
                   help="tail one line from this file as 'last_incident'")
    p.add_argument("--dry-run", action="store_true",
                   help="print rendered text to stdout, do not write")
    p.add_argument("--check", action="store_true",
                   help="exit 0 if target matches rendered, 1 otherwise (CI use)")
    args = p.parse_args()

    target = args.target
    if target is None:
        agent_dir = os.environ.get("OPSKEEPER_PI_AGENT_DIR")
        target = (Path(agent_dir) / "agents" / "opskeeper-monitor.md") if agent_dir else (
            REPO_ROOT / DEFAULT_TARGET_REL
        )

    rendered = render(args.source, target, args.incident_log)

    if args.dry_run:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        if not target.exists():
            print(f"missing: {target}", file=sys.stderr)
            return 1
        # Normalize the snapshot timestamp in both the rendered output
        # and the on-disk file so that --check can succeed across runs
        # without requiring a per-second freeze. We compare the body
        # text below the snapshot line — anything else is real drift.
        import re as _re
        on_disk = target.read_text(encoding="utf-8")
        rendered_no_ts = _re.sub(r"^# opskeeper-monitor snapshot @ .+$",
                                 "# opskeeper-monitor snapshot @ <normalized>",
                                 rendered, count=1, flags=_re.MULTILINE)
        on_disk_no_ts = _re.sub(r"^# opskeeper-monitor snapshot @ .+$",
                                "# opskeeper-monitor snapshot @ <normalized>",
                                on_disk, count=1, flags=_re.MULTILINE)
        if rendered_no_ts != on_disk_no_ts:
            print(f"drift: {target} differs from rendered output", file=sys.stderr)
            return 1
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    # ensure file mode 0644
    target.chmod(0o644)
    print(f"wrote {target} ({len(rendered)} bytes, snapshot {json.dumps(_host_snapshot())})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
