#!/usr/bin/env bash
# Copy the canonical PiG extensions into the packages a node installs.
#
# Every package under plugins/pig-ops/ ships its extensions as source,
# because the agent runtime builds them on the node it runs on and a node
# has no access to an unpublished OpsKeeper module. That necessity is the
# whole reason this script exists: the copies are unavoidable, and a hand
# copy is how they drift.
#
# So the copies are generated, and the drift tests in
# core/floor/pluginmanifest are the check that this script was run. Run
# this after touching anything under core/pig/extensions/, then run the
# tests. Editing a packaged file directly is always wrong — the next run
# of this script overwrites it, which is the intended outcome.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

canonical_root="core/pig/extensions"
packages_root="plugins/pig-ops"

if [[ ! -d "$canonical_root" || ! -d "$packages_root" ]]; then
	echo "sync-pig-ops: expected $canonical_root and $packages_root under $repo_root" >&2
	exit 1
fi

copied=0
for pkg_dir in "$packages_root"/*/; do
	[[ -d "$pkg_dir" ]] || continue
	pkg="$(basename "$pkg_dir")"
	exts_dir="$pkg_dir/extensions"
	[[ -d "$exts_dir" ]] || continue

	for ext_dir in "$exts_dir"/*/; do
		[[ -d "$ext_dir" ]] || continue
		ext="$(basename "$ext_dir")"
		src="$canonical_root/$ext"

		if [[ ! -d "$src" ]]; then
			echo "sync-pig-ops: $pkg ships extensions/$ext but core/pig/extensions/$ext does not exist" >&2
			echo "               a package may only ship extensions that have a canonical source" >&2
			exit 1
		fi

		# The Go sources, minus the tests: a node builds the extension, it
		# does not run its unit tests, and shipping them would mean
		# shipping a dependency on the opskeeper skill registry that the
		# extension deliberately does not have.
		for go_src in "$src"/*.go; do
			[[ -e "$go_src" ]] || continue
			base="$(basename "$go_src")"
			[[ "$base" == *_test.go ]] && continue
			cp "$go_src" "$ext_dir/$base"
			copied=$((copied + 1))
		done

		# The go.mod, rewritten. Two things change and only two: the module
		# path moves under the package that ships it, and the replace
		# block is dropped. A node has no local checkout of OpsKeeper and
		# no local checkout of a pre-stable PiG, so a replace directive
		# here would send the node's build to a path that does not exist
		# on it.
		{
			echo "// $(echo "$ext" | tr '_' '-'), as the agent runtime builds it on a node."
			echo "//"
			echo "// GENERATED by scripts/sync-pig-ops.sh from $src."
			echo "// Do not edit: the next run overwrites this file, and"
			echo "// TestThePackagedExtensionMatchesTheCanonicalSource fails if it drifts."
			echo "//"
			echo "// The copy is deliberate. The agent builds extensions from source on"
			echo "// the node it runs on, and a node has no access to an unpublished"
			echo "// OpsKeeper module. A package that referenced the canonical path"
			echo "// would install and then fail to build, which is the worst time to"
			echo "// find out."
			echo "module github.com/vincent-wuhan/opskeeper/$packages_root/$pkg/extensions/$ext"
			echo
			echo "go 1.26.0"
			echo
			echo "require ("
			echo "	github.com/MichaelKinsy/PiG/extensions/sdk v0.3.0"
			echo "	github.com/vincent-wuhan/opskeeper/core v0.0.0"
			echo ")"
		} > "$ext_dir/go.mod"

		copied=$((copied + 1))
		echo "  $pkg <- $ext"
	done
done

echo "sync-pig-ops: wrote $copied files"
